config/routes.rb
SampleApp::Application.routes.draw do
  resources :orcs

end

app/models/orc.rb
class Orc < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orcs_controller.rb
class OrcsController < ApplicationController
  # GET /orcs
  # GET /orcs.json
  def index
    @orcs = Orc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orcs }
    end
  end

  # GET /orcs/1
  # GET /orcs/1.json
  def show
    @orc = Orc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orc }
    end
  end

  # GET /orcs/new
  # GET /orcs/new.json
  def new
    @orc = Orc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orc }
    end
  end

  # GET /orcs/1/edit
  def edit
    @orc = Orc.find(params[:id])
  end

  # POST /orcs
  # POST /orcs.json
  def create
    @orc = Orc.new(params[:orc])

    respond_to do |format|
      if @orc.save
        format.html { redirect_to @orc, notice: 'Orc was successfully created.' }
        format.json { render json: @orc, status: :created, location: @orc }
      else
        format.html { render action: "new" }
        format.json { render json: @orc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orcs/1
  # PUT /orcs/1.json
  def update
    @orc = Orc.find(params[:id])

    respond_to do |format|
      if @orc.update_attributes(params[:orc])
        format.html { redirect_to @orc, notice: 'Orc was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @orc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orcs/1
  # DELETE /orcs/1.json
  def destroy
    @orc = Orc.find(params[:id])
    @orc.destroy

    respond_to do |format|
      format.html { redirect_to orcs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orcs_helper.rb
module OrcsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orcs/_form.html.erb
<%= form_for(@orc) do |f| %>
  <% if @orc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orc.errors.count, "error") %> prohibited this orc from being saved:</h2>

      <ul>
      <% @orc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lv %><br />
    <%= f.number_field :lv %>
  </div>
  <div class="field">
    <%= f.label :weapon %><br />
    <%= f.text_field :weapon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orcs/edit.html.erb
<h1>Editing orc</h1>

<%= render 'form' %>

<%= link_to 'Show', @orc %> |
<%= link_to 'Back', orcs_path %>

app/views/orcs/index.html.erb
<h1>Listing orcs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lv</th>
    <th>Weapon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orcs.each do |orc| %>
  <tr>
    <td><%= orc.name %></td>
    <td><%= orc.lv %></td>
    <td><%= orc.weapon %></td>
    <td><%= link_to 'Show', orc %></td>
    <td><%= link_to 'Edit', edit_orc_path(orc) %></td>
    <td><%= link_to 'Destroy', orc, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Orc', new_orc_path %>

app/views/orcs/new.html.erb
<h1>New orc</h1>

<%= render 'form' %>

<%= link_to 'Back', orcs_path %>

app/views/orcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @orc.name %>
</p>

<p>
  <b>Lv:</b>
  <%= @orc.lv %>
</p>

<p>
  <b>Weapon:</b>
  <%= @orc.weapon %>
</p>


<%= link_to 'Edit', edit_orc_path(@orc) %> |
<%= link_to 'Back', orcs_path %>